export const REQUEST_CONFIG = 'REQUEST_CONFIG';
export const RECEIVE_CONFIG = 'RECEIVE_CONFIG';
export const REQUEST_CONFIG_FAILURE = 'REQUEST_CONFIG_FAILURE';

export const REQUEST_VALIDATION_NEW_USER = 'REQUEST_VALIDATION_NEW_USER';
export const RECEIVE_VALIDATION_NEW_USER = 'RECEIVE_VALIDATION_NEW_USER';
export const REQUEST_VALIDATION_NEW_USER_FAILURE = 'REQUEST_VALIDATION_NEW_USER_FAILURE';

export const STORE_VALID_EMAIL = 'STORE_VALID_EMAIL';
export const STORE_EMAIL_ERROR = 'STORE_EMAIL_ERROR';

export const STORE_VALID_ADDRESS = 'STORE_VALID_ADDRESS';
export const STORE_ADDRESS_ERRORS = 'STORE_ADDRESS_ERRORS';
export const STORE_SAVE_ADDRESS = 'STORE_SAVE_ADDRESS';

export const STORE_SUBSCRIBE_TO_NEWSLETTER = 'STORE_SUBSCRIBE_TO_NEWSLETTER';
export const STORE_PASSWORD = 'STORE_PASSWORD';
export const STORE_PASSWORD_ERROR = 'STORE_PASSWORD_ERROR';

export const STEP1_CONDITION_CHANGE = 'STEP1_CONDITION_CHANGE';
export const STEP2_CONDITION_CHANGE = 'STEP2_CONDITION_CHANGE';
export const STEP3_CONDITION_CHANGE = 'STEP3_CONDITION_CHANGE';

export const SCROLL_TO_CHANGE = 'SCROLL_TO_CHANGE';

export const STEP1_OVERLAY_STATE_CHANGE = 'STEP1_OVERLAY_STATE_CHANGE';

export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const RECEIVE_COUNTRIES = 'RECEIVE_COUNTRIES';
export const REQUEST_COUNTRIES_FAILURE = 'REQUEST_COUNTRIES_FAILURE';

export const REQUEST_COUNTRIES_BY_CODE = 'REQUEST_COUNTRIES_BY_CODE';
export const RECEIVE_COUNTRIES_BY_CODE = 'RECEIVE_COUNTRIES_BY_CODE';
export const REQUEST_COUNTRIES_BY_CODE_FAILURE = 'REQUEST_COUNTRIES_BY_CODE_FAILURE';

export const REQUEST_PLACE_ORDER = 'REQUEST_PLACE_ORDER';
export const REQUEST_PLACE_ORDER_FAILURE = 'REQUEST_PLACE_ORDER_FAILURE';
export const RECEIVE_PLACE_ORDER = 'RECEIVE_PLACE_ORDER';

export const TOGGLE_ERROR_BANNER = 'TOGGLE_ERROR_BANNER';
export const TOGGLE_COMPANY_SIZE_ERROR = 'TOGGLE_COMPANY_SIZE_ERROR';
export const STORE_COMPANY_SIZE = 'STORE_COMPANY_SIZE';
export const SHOW_APP_INIT_ERROR_BANNER = 'SHOW_APP_INIT_ERROR_BANNER';
