export const INVALID_EMAIL = 'INVALID_EMAIL';
export const EMPTY_EMAIL = 'EMPTY_EMAIL';
export const ACCOUNT_EXISTS = 'ACCOUNT_EXISTS';

export const EMPTY_FIRST_NAME = 'EMPTY_FIRST_NAME';
export const EMPTY_LAST_NAME = 'EMPTY_LAST_NAME';
export const EMPTY_ADDRESS_LINE_1 = 'EMPTY_ADDRESS_LINE_1';
export const EMPTY_TOWN = 'EMPTY_TOWN';
export const EMPTY_REGION = 'EMPTY_REGION';
export const EMPTY_POSTCODE = 'EMPTY_POSTCODE';
export const EMPTY_TELEPHONE_NUMBER = 'EMPTY_TELEPHONE_NUMBER';

export const INVALID_FIRST_NAME = 'INVALID_FIRST_NAME';
export const INVALID_LAST_NAME = 'INVALID_LAST_NAME';
export const INVALID_COMPANY = 'INVALID_COMPANY';
export const INVALID_ADDRESS_LINE_1 = 'INVALID_ADDRESS_LINE_1';
export const INVALID_ADDRESS_LINE_2 = 'INVALID_ADDRESS_LINE_2';
export const INVALID_TOWN = 'INVALID_TOWN';
export const INVALID_REGION = 'INVALID_REGION';
export const INVALID_POSTCODE = 'INVALID_POSTCODE';
export const INVALID_TELEPHONE_NUMBER = 'INVALID_TELEPHONE_NUMBER';

export const EMPTY_PASSWORD = 'EMPTY_PASSWORD';
export const INVALID_PASSWORD = 'INVALID_PASSWORD';
export const EMPTY_COMPANY_SIZE = 'EMPTY_COMPANY_SIZE';

export const EMPTY_COUNTRY = 'EMPTY_COUNTRY';
export const EMPTY_ADDRESS = 'EMPTY_ADDRESS';
export const EMPTY_USER_DETAILS = 'EMPTY_USER_DETAILS';

export const UNSUPPORTED_SHIPPING_COUNTRY = 'UNSUPPORTED_SHIPPING_COUNTRY';
export const UNSUPPORTED_WEBSITE = 'UNSUPPORTED_WEBSITE';
export const OUT_OF_STOCK = 'OUT_OF_STOCK';
